spring:
    freemarker:
        suffix: .ftl
server:
    servlet:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
    port: 8080
dubbo:
    application:
        name: shop-frontend
        qos-port: 20991
        qos-accept-foreign-ip: true
        qos-anonymous-allow-commands: metrics
    protocol:
        name: dubbo
        port: 20881
    provider:
        token: true
    registry:
#        address: zookeeper://127.0.0.1:2181
        address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
    config-center:
        address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
    metadata-report:
        address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
        port: 8848
    metrics:
        aggregation:
            enabled: true
        histogram:
            enabled: true
            enabled-percentiles: true
        enable-jvm: true
        enable-threadpool: true
        enable-registry: true
        enable-metadata: true
    tracing:
        enabled: true # default is false
        sampling:
            probability: 0.5 # sampling rate, default is 0.1
        propagation:
            type: W3C # W3C/B3 default is W3C
        tracing-exporter:
            otlp-config:
                endpoint: http://localhost:4317
                timeout: 10s # default is 10s
                compression-method: none # none/gzip The method used to compress payloads, default is "none"

nacos:
  address: 47.94.36.22