dubbo:
    application:
        name: shop-user
        qos-port: 20994
        qos-anonymous-allow-commands: metrics
        qos-anonymous-access-permission-level: PROTECTED
    protocol:
        port: 20884
    provider:
        token: true
    registry:
#        address: zookeeper://127.0.0.1:2181
        address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
    config-center:
        address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
    metadata-report:
        address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
        port: 8848
    metrics:
        aggregation:
            enabled: true
        histogram:
            enabled: true
            enabled-percentiles: true
        enable-jvm: true
        enable-threadpool: true
        enable-registry: true
        enable-metadata: true
    tracing:
        enabled: true # default is false
        sampling:
            probability: 0.5 # sampling rate, default is 0.1
        propagation:
            type: W3C # W3C/B3 default is W3C
        tracing-exporter:
            otlp-config:
                endpoint: http://118.190.145.187:4317
                timeout: 10s # default is 10s
                compression-method: none # none/gzip The method used to compress payloads, default is "none"
                headers: # customized added headers, default is empty
                    auth:
nacos:
    address: 47.104.241.242